spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cde-account-service
  redis:
    host: 192.168.1.10
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0 

account: 
  i18n: 
    messages:
      basename: i18n/messages
    
logging:
  file: my.log
  
debug: true

#eureka:
#  instance:
#    hostname: account-service
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-server-1:8761/eureka/,http://discovery-server-2:8762/eureka/
#---
# mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=primary"
#spring:
#  profiles: primary
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: account-service-1
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server-2:8762/eureka/
#
#---
## mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=secondary"
#spring:
#  profiles: secondary
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: account-service-2
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server-1:8761/eureka/

