spring:
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/solution-server?characterEncoding=utf8&useSSL=true
    username: root
    password: mytest
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl: 
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  redis:
    host: 192.168.1.10
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0 
  output:
    ansi:
      enabled: DETECT
  mail:
    host: smtp.gmail.com
    username: lichanglin.lcl@gmail.com
    password: lcl19930907
    port: 587
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
            required: true
            
        