spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cde-account-service
  redis:
    host: 192.168.1.10
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0 

cde:
  account:
    i18n:
      messages:
        basename: i18n/messages



