spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cde-account-service
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0 
      
cde:
  account:
    i18n:
      messages:
        basename: i18n/messages
    filter: 
      origin: "*" 
      methods: "POST, GET, OPTIONS, PUT, DELETE" 
      headers: "Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Max-Age,Content-Type" 
      content-type: "application/json" 

server:
  port: 8080


