spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cde-account-service
  redis:
    host: 192.168.1.10
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0 
  output:
    ansi:
      enabled: DETECT
  mail:
    host: smtp.gmail.com
    username: lichanglin.lcl@gmail.com
    password: lcl19930907d
    port: 587
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
            required: true
            
        